apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # !
  ports:
  - port: 80 # porta p√∫blica
    targetPort: 80 # porta onde nosso nginx escuta
  selector:
    app: frontend